include ':vector-app'
include ':vector'
include ':vector-config'

include ':library:core-utils'
include ':library:ui-strings'
include ':library:ui-styles'
include ':library:attachment-viewer'
include ':library:multipicker'
include ':library:media-transcode'
include ':library:animated-image'

include ':library:external:jsonviewer'
include ':library:external:diff-match-patch'
include ':library:external:textdrawable'
include ':library:external:autocomplete'
include ':library:external:span'
include ':library:external:openpgp-api'
include ':library:external:markwon-html'
include ':library:external:barcodescanner:core'
include ':library:external:barcodescanner:zxing'

include ':library:external:libce'
project(':library:external:libce').projectDir = new File(rootProject.projectDir, 'library/external/libce/android/olm-sdk')
include ':library:external:olm-jvm'
include ':library:external:timber-jvm'
include ':matrix-sdk-core'
include ':library:external:libopus'
include ':matrix-sdk-android'
include ':matrix-sdk-android-flow'
include ':matrix-sdk-desktop'
include ':samples:matrix-cli'
